/**
 * Copy local SQLite (backend/db.sqlite) into Neon Postgres.
 *
 * Run from the backend package:
 *   PROD_DATABASE_URL="postgresql://..." CONFIRM_OVERWRITE=yes npm run copy-db:prod
 *
 * Windows PowerShell:
 *   $env:PROD_DATABASE_URL="postgresql://..."
 *   $env:CONFIRM_OVERWRITE="yes"
 *   npm run copy-db:prod
 */
import 'dotenv/config';
import * as fs from 'fs';
import * as path from 'path';
import sqlite3 = require('sqlite3');
import { Client } from 'pg';

const TABLES_IN_INSERT_ORDER = [
  'user',
  'user_settings',
  'phases',
  'tasks',
  'task_phases',
  'scheduled_tasks',
  'schedule_jobs',
  'event_phases',
] as const;

const BOOLEAN_COLUMNS = new Set([
  'isEmailVerified',
  'isRecurring',
  'allowSplit',
  'isFixedExternal',
  'weekendWorkEnabled',
  'googleCalendarLinked',
  'allowSplitScheduling',
  'isAutoGenerated',
]);

const JSON_COLUMNS = new Set(['weekDays', 'recurrenceWeekDays']);

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function sqliteAll<T = Record<string, unknown>>(
  db: sqlite3.Database,
  sql: string,
  params: unknown[] = [],
): Promise<T[]> {
  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) reject(err);
      else resolve(rows as T[]);
    });
  });
}

function coerceValue(column: string, value: unknown): unknown {
  if (value === null || value === undefined) {
    return null;
  }
  if (BOOLEAN_COLUMNS.has(column)) {
    return value === true || value === 1 || value === '1';
  }
  if (JSON_COLUMNS.has(column)) {
    if (value === '') {
      return null;
    }
    let parsed: unknown = value;
    if (typeof value === 'string') {
      try {
        parsed = JSON.parse(value);
      } catch {
        return null;
      }
    }
    return JSON.stringify(parsed);
  }
  return value;
}

async function copyTable(
  sqliteDb: sqlite3.Database,
  pg: Client,
  table: string,
): Promise<number> {
  const rows = await sqliteAll<Record<string, unknown>>(
    sqliteDb,
    `SELECT * FROM ${quoteIdent(table)}`,
  );
  if (rows.length === 0) {
    console.log(`  ${table}: 0 rows`);
    return 0;
  }

  const pgColumnsResult = await pg.query<{ column_name: string }>(
    `SELECT column_name
     FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = $1`,
    [table],
  );
  const pgColumns = new Set(pgColumnsResult.rows.map((r) => r.column_name));
  if (pgColumns.size === 0) {
    throw new Error(
      `Postgres has no table "${table}". Start the Render API once so TypeORM can create the schema.`,
    );
  }

  const sourceColumns = Object.keys(rows[0]).filter((col) => pgColumns.has(col));
  if (sourceColumns.length === 0) {
    throw new Error(`No overlapping columns for table "${table}"`);
  }

  const colSql = sourceColumns.map(quoteIdent).join(', ');
  const placeholders = sourceColumns.map((_, i) => `$${i + 1}`).join(', ');
  const insertSql = `INSERT INTO ${quoteIdent(table)} (${colSql}) VALUES (${placeholders})`;

  if (table === 'phases') {
    for (const row of rows) {
      const withoutParent = {
        ...row,
        parentPhaseId: null,
      };
      const values = sourceColumns.map((col) => coerceValue(col, withoutParent[col]));
      await pg.query(insertSql, values);
    }
    for (const row of rows) {
      if (row.parentPhaseId == null || row.parentPhaseId === '') {
        continue;
      }
      await pg.query(
        `UPDATE ${quoteIdent('phases')} SET ${quoteIdent('parentPhaseId')} = $1 WHERE ${quoteIdent('id')} = $2`,
        [row.parentPhaseId, row.id],
      );
    }
    console.log(`  ${table}: ${rows.length} rows (parent ids applied in a second pass)`);
    return rows.length;
  }

  for (const row of rows) {
    const values = sourceColumns.map((col) => coerceValue(col, row[col]));
    await pg.query(insertSql, values);
  }
  console.log(`  ${table}: ${rows.length} rows`);
  return rows.length;
}

async function main() {
  const sqlitePath = path.resolve(
    process.env.SQLITE_PATH || path.join(process.cwd(), 'db.sqlite'),
  );
  const prodUrl = process.env.PROD_DATABASE_URL;
  if (!prodUrl || !/^postgres(ql)?:\/\//i.test(prodUrl)) {
    throw new Error(
      'Set PROD_DATABASE_URL to the Neon connection string (postgresql://…?sslmode=require).',
    );
  }
  if (process.env.CONFIRM_OVERWRITE !== 'yes') {
    throw new Error(
      'This replaces production data. Re-run with CONFIRM_OVERWRITE=yes',
    );
  }
  if (!fs.existsSync(sqlitePath)) {
    throw new Error(`SQLite file not found: ${sqlitePath}`);
  }

  const sqliteDb = new sqlite3.Database(sqlitePath);
  const pg = new Client({
    connectionString: prodUrl,
    ssl: { rejectUnauthorized: false },
  });
  await pg.connect();

  try {
    console.log(`Source: ${sqlitePath}`);
    console.log('Wiping production tables…');
    await pg.query(
      `TRUNCATE TABLE ${TABLES_IN_INSERT_ORDER.map(quoteIdent).reverse().join(', ')} RESTART IDENTITY CASCADE`,
    );

    console.log('Copying…');
    for (const table of TABLES_IN_INSERT_ORDER) {
      await copyTable(sqliteDb, pg, table);
    }
    console.log('Done. Log in again on production (JWT secret differs from local).');
  } finally {
    await pg.end();
    sqliteDb.close();
  }
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
