import {
  IsNotEmpty,
  IsUUID,
  IsDateString,
  IsBoolean,
  IsOptional,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class CreateScheduleDto {
  @ApiProperty({
    description: 'Task ID',
    example: 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
  })
  @IsNotEmpty()
  @IsUUID()
  taskId: string;

  @ApiProperty({
    description: 'Scheduled start time',
    example: '2025-05-15T09:00:00.000Z',
  })
  @IsNotEmpty()
  @IsDateString()
  scheduledStartTime: string;

  @ApiProperty({
    description: 'Scheduled end time',
    example: '2025-05-15T10:00:00.000Z',
  })
  @IsNotEmpty()
  @IsDateString()
  scheduledEndTime: string;

  @ApiProperty({
    description: 'Whether this slot was auto-generated',
    example: true,
    required: false,
  })
  @IsOptional()
  @IsBoolean()
  isAutoGenerated?: boolean;

  @ApiProperty({
    description: 'Generation run identifier',
    example: 'weekly-generation-20250510',
    required: false,
  })
  @IsOptional()
  generationRun?: string;
}
