import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { timestampColumnType } from '../../database/column-types';
import { Task } from '../tasks/entities/task.entity';

@Entity('scheduled_tasks')
export class ScheduledTask {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  taskId: string;

  @ManyToOne(() => Task, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'taskId' })
  task: Task;

  @Column({ type: timestampColumnType() })
  scheduledStartTime: Date;

  @Column({ type: timestampColumnType() })
  scheduledEndTime: Date;

  @Column({ default: false })
  isAutoGenerated: boolean;

  @Column({ type: 'varchar', length: 128, nullable: true })
  generationRun: string | null;

  /** Google event for this segment, or shared RRULE master id for recurring tasks. */
  @Column({ type: 'varchar', nullable: true })
  googleEventId: string | null;

  @Column({ type: 'varchar', length: 255, nullable: true })
  googleEventCalendarId: string | null;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
