export const INVALID_JWT = 'INVALID_JWT';
export const EMPTY_JWT = 'EMPTY_JWT';
export const INVALID_SESSION = 'INVALID_SESSION';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';

export const INVALID_EMAIL = 'INVALID_EMAIL';
export const EMPTY_EMAIL = 'EMPTY_EMAIL';
export const UNKNOWN_EMAIL = 'UNKNOWN_EMAIL';

export const PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT';
export const PASSWORDS_DO_NOT_MATCH = 'PASSWORDS_DO_NOT_MATCH';
export const PASSWORD_WAS_PREVIOUSLY_USED = 'PASSWORD_WAS_PREVIOUSLY_USED';

export const INVALID_VERIFICATION_CODE = 'INVALID_VERIFICATION_CODE';
export const VERIFICATION_CODE_EXPIRED = 'VERIFICATION_CODE_EXPIRED';

export const EMAIL_ALREADY_TAKEN = 'EMAIL_ALREADY_TAKEN';