export const WRONG_PASSWORD_ERROR = 'WRONG_PASSWORD_ERROR';
export const USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR';
export const INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR';
export const USER_ALREADY_EXISTS_ERROR = 'USER_ALREADY_EXISTS_ERROR';
export const INVALID_EMAIL_FORMAT_ERROR = 'INVALID_EMAIL_FORMAT_ERROR';
export const INVALID_JWT = 'INVALID_JWT';
export const EMPTY_JWT = 'EMPTY_JWT';
export const INVALID_SESSION = 'INVALID_SESSION';
export const INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';

export const errorsList = {
    [WRONG_PASSWORD_ERROR]: 800,
    [USER_NOT_FOUND_ERROR]: 801,
    [INVALID_TOKEN_ERROR]: 802,
    [USER_ALREADY_EXISTS_ERROR]: 803,
    [INVALID_EMAIL_FORMAT_ERROR]: 804,
    [INVALID_JWT]: 805,
    [EMPTY_JWT]: 806,
    [INVALID_SESSION]: 807,
    [INVALID_REFRESH_TOKEN]: 808,
    [INVALID_CREDENTIALS]: 809,
}; 